/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MEXC P2P Aggregator
 * Read-only P2P advertisement monitoring for MEXC
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";
import { unref } from "vue";
import type { MaybeRef } from "vue";
import type {
  AppSchemasProfileErrorResponse,
  BanksListResponse,
  HTTPValidationError,
  OnboardingRequest,
  SavedFiltersResponse,
  SavedFiltersUpdate,
  TraderProfileResponse,
  TraderProfileUpdate,
} from "../client.schemas";
import { customMutator } from ".././mutator";

/**
 * Get current user's trader profile.

Creates default profile if none exists.
 * @summary Get Profile
 */
export const getProfileApiV1ProfileGet = (signal?: AbortSignal) => {
  return customMutator<TraderProfileResponse>({
    url: `/api/v1/profile/`,
    method: "GET",
    signal,
  });
};

export const getGetProfileApiV1ProfileGetQueryKey = () => {
  return ["api", "v1", "profile"] as const;
};

export const getGetProfileApiV1ProfileGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getProfileApiV1ProfileGet>>,
  TError = AppSchemasProfileErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getProfileApiV1ProfileGet>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getGetProfileApiV1ProfileGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProfileApiV1ProfileGet>>
  > = ({ signal }) => getProfileApiV1ProfileGet(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProfileApiV1ProfileGet>>,
    TError,
    TData
  >;
};

export type GetProfileApiV1ProfileGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProfileApiV1ProfileGet>>
>;
export type GetProfileApiV1ProfileGetQueryError =
  AppSchemasProfileErrorResponse;

/**
 * @summary Get Profile
 */
export const useGetProfileApiV1ProfileGet = <
  TData = Awaited<ReturnType<typeof getProfileApiV1ProfileGet>>,
  TError = AppSchemasProfileErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getProfileApiV1ProfileGet>>,
      TError,
      TData
    >
  >;
}): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetProfileApiV1ProfileGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
};

/**
 * Update current user's trader profile.

Only provided fields are updated.
 * @summary Update Profile
 */
export const updateProfileApiV1ProfilePut = (
  traderProfileUpdate: MaybeRef<TraderProfileUpdate>,
) => {
  traderProfileUpdate = unref(traderProfileUpdate);

  return customMutator<TraderProfileResponse>({
    url: `/api/v1/profile/`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: traderProfileUpdate,
  });
};

export const getUpdateProfileApiV1ProfilePutMutationOptions = <
  TError = AppSchemasProfileErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProfileApiV1ProfilePut>>,
    TError,
    { data: TraderProfileUpdate },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProfileApiV1ProfilePut>>,
  TError,
  { data: TraderProfileUpdate },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProfileApiV1ProfilePut>>,
    { data: TraderProfileUpdate }
  > = (props) => {
    const { data } = props ?? {};

    return updateProfileApiV1ProfilePut(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateProfileApiV1ProfilePutMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateProfileApiV1ProfilePut>>
>;
export type UpdateProfileApiV1ProfilePutMutationBody = TraderProfileUpdate;
export type UpdateProfileApiV1ProfilePutMutationError =
  AppSchemasProfileErrorResponse;

/**
 * @summary Update Profile
 */
export const useUpdateProfileApiV1ProfilePut = <
  TError = AppSchemasProfileErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProfileApiV1ProfilePut>>,
    TError,
    { data: TraderProfileUpdate },
    TContext
  >;
}): UseMutationReturnType<
  Awaited<ReturnType<typeof updateProfileApiV1ProfilePut>>,
  TError,
  { data: TraderProfileUpdate },
  TContext
> => {
  const mutationOptions =
    getUpdateProfileApiV1ProfilePutMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Get list of available banks and payment methods.
 * @summary Get Banks
 */
export const getBanksApiV1ProfileBanksGet = (signal?: AbortSignal) => {
  return customMutator<BanksListResponse>({
    url: `/api/v1/profile/banks`,
    method: "GET",
    signal,
  });
};

export const getGetBanksApiV1ProfileBanksGetQueryKey = () => {
  return ["api", "v1", "profile", "banks"] as const;
};

export const getGetBanksApiV1ProfileBanksGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getBanksApiV1ProfileBanksGet>>,
  TError = AppSchemasProfileErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getBanksApiV1ProfileBanksGet>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getGetBanksApiV1ProfileBanksGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getBanksApiV1ProfileBanksGet>>
  > = ({ signal }) => getBanksApiV1ProfileBanksGet(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getBanksApiV1ProfileBanksGet>>,
    TError,
    TData
  >;
};

export type GetBanksApiV1ProfileBanksGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBanksApiV1ProfileBanksGet>>
>;
export type GetBanksApiV1ProfileBanksGetQueryError =
  AppSchemasProfileErrorResponse;

/**
 * @summary Get Banks
 */
export const useGetBanksApiV1ProfileBanksGet = <
  TData = Awaited<ReturnType<typeof getBanksApiV1ProfileBanksGet>>,
  TError = AppSchemasProfileErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getBanksApiV1ProfileBanksGet>>,
      TError,
      TData
    >
  >;
}): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetBanksApiV1ProfileBanksGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
};

/**
 * Get current user's saved advertisement filters.
 * @summary Get Saved Filters
 */
export const getSavedFiltersApiV1ProfileFiltersGet = (signal?: AbortSignal) => {
  return customMutator<SavedFiltersResponse>({
    url: `/api/v1/profile/filters`,
    method: "GET",
    signal,
  });
};

export const getGetSavedFiltersApiV1ProfileFiltersGetQueryKey = () => {
  return ["api", "v1", "profile", "filters"] as const;
};

export const getGetSavedFiltersApiV1ProfileFiltersGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getSavedFiltersApiV1ProfileFiltersGet>>,
  TError = AppSchemasProfileErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getSavedFiltersApiV1ProfileFiltersGet>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getGetSavedFiltersApiV1ProfileFiltersGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSavedFiltersApiV1ProfileFiltersGet>>
  > = ({ signal }) => getSavedFiltersApiV1ProfileFiltersGet(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSavedFiltersApiV1ProfileFiltersGet>>,
    TError,
    TData
  >;
};

export type GetSavedFiltersApiV1ProfileFiltersGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSavedFiltersApiV1ProfileFiltersGet>>
>;
export type GetSavedFiltersApiV1ProfileFiltersGetQueryError =
  AppSchemasProfileErrorResponse;

/**
 * @summary Get Saved Filters
 */
export const useGetSavedFiltersApiV1ProfileFiltersGet = <
  TData = Awaited<ReturnType<typeof getSavedFiltersApiV1ProfileFiltersGet>>,
  TError = AppSchemasProfileErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getSavedFiltersApiV1ProfileFiltersGet>>,
      TError,
      TData
    >
  >;
}): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getGetSavedFiltersApiV1ProfileFiltersGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
};

/**
 * Save advertisement filters for current user.

Replaces existing filters.
 * @summary Update Saved Filters
 */
export const updateSavedFiltersApiV1ProfileFiltersPut = (
  savedFiltersUpdate: MaybeRef<SavedFiltersUpdate>,
) => {
  savedFiltersUpdate = unref(savedFiltersUpdate);

  return customMutator<SavedFiltersResponse>({
    url: `/api/v1/profile/filters`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: savedFiltersUpdate,
  });
};

export const getUpdateSavedFiltersApiV1ProfileFiltersPutMutationOptions = <
  TError = AppSchemasProfileErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateSavedFiltersApiV1ProfileFiltersPut>>,
    TError,
    { data: SavedFiltersUpdate },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateSavedFiltersApiV1ProfileFiltersPut>>,
  TError,
  { data: SavedFiltersUpdate },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateSavedFiltersApiV1ProfileFiltersPut>>,
    { data: SavedFiltersUpdate }
  > = (props) => {
    const { data } = props ?? {};

    return updateSavedFiltersApiV1ProfileFiltersPut(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateSavedFiltersApiV1ProfileFiltersPutMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof updateSavedFiltersApiV1ProfileFiltersPut>>
  >;
export type UpdateSavedFiltersApiV1ProfileFiltersPutMutationBody =
  SavedFiltersUpdate;
export type UpdateSavedFiltersApiV1ProfileFiltersPutMutationError =
  AppSchemasProfileErrorResponse;

/**
 * @summary Update Saved Filters
 */
export const useUpdateSavedFiltersApiV1ProfileFiltersPut = <
  TError = AppSchemasProfileErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateSavedFiltersApiV1ProfileFiltersPut>>,
    TError,
    { data: SavedFiltersUpdate },
    TContext
  >;
}): UseMutationReturnType<
  Awaited<ReturnType<typeof updateSavedFiltersApiV1ProfileFiltersPut>>,
  TError,
  { data: SavedFiltersUpdate },
  TContext
> => {
  const mutationOptions =
    getUpdateSavedFiltersApiV1ProfileFiltersPutMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Complete onboarding wizard.

Sets up trader profile and marks onboarding as completed.
 * @summary Complete Onboarding
 */
export const completeOnboardingApiV1ProfileOnboardingPost = (
  onboardingRequest: MaybeRef<OnboardingRequest>,
) => {
  onboardingRequest = unref(onboardingRequest);

  return customMutator<TraderProfileResponse>({
    url: `/api/v1/profile/onboarding`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: onboardingRequest,
  });
};

export const getCompleteOnboardingApiV1ProfileOnboardingPostMutationOptions = <
  TError = AppSchemasProfileErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof completeOnboardingApiV1ProfileOnboardingPost>>,
    TError,
    { data: OnboardingRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof completeOnboardingApiV1ProfileOnboardingPost>>,
  TError,
  { data: OnboardingRequest },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof completeOnboardingApiV1ProfileOnboardingPost>>,
    { data: OnboardingRequest }
  > = (props) => {
    const { data } = props ?? {};

    return completeOnboardingApiV1ProfileOnboardingPost(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompleteOnboardingApiV1ProfileOnboardingPostMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof completeOnboardingApiV1ProfileOnboardingPost>>
  >;
export type CompleteOnboardingApiV1ProfileOnboardingPostMutationBody =
  OnboardingRequest;
export type CompleteOnboardingApiV1ProfileOnboardingPostMutationError =
  | AppSchemasProfileErrorResponse
  | HTTPValidationError;

/**
 * @summary Complete Onboarding
 */
export const useCompleteOnboardingApiV1ProfileOnboardingPost = <
  TError = AppSchemasProfileErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof completeOnboardingApiV1ProfileOnboardingPost>>,
    TError,
    { data: OnboardingRequest },
    TContext
  >;
}): UseMutationReturnType<
  Awaited<ReturnType<typeof completeOnboardingApiV1ProfileOnboardingPost>>,
  TError,
  { data: OnboardingRequest },
  TContext
> => {
  const mutationOptions =
    getCompleteOnboardingApiV1ProfileOnboardingPostMutationOptions(options);

  return useMutation(mutationOptions);
};
