/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MEXC P2P Aggregator
 * Read-only P2P advertisement monitoring for MEXC
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/vue-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";
import { unref } from "vue";
import type { HealthHealthGet200 } from "../client.schemas";
import { customMutator } from ".././mutator";

/**
 * Check DB and Redis connectivity, return aggregated status.
 * @summary Health
 */
export const healthHealthGet = (signal?: AbortSignal) => {
  return customMutator<HealthHealthGet200>({
    url: `/health`,
    method: "GET",
    signal,
  });
};

export const getHealthHealthGetQueryKey = () => {
  return ["health"] as const;
};

export const getHealthHealthGetQueryOptions = <
  TData = Awaited<ReturnType<typeof healthHealthGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getHealthHealthGetQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthHealthGet>>> = ({
    signal,
  }) => healthHealthGet(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthHealthGet>>,
    TError,
    TData
  >;
};

export type HealthHealthGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthHealthGet>>
>;
export type HealthHealthGetQueryError = unknown;

/**
 * @summary Health
 */
export const useHealthHealthGet = <
  TData = Awaited<ReturnType<typeof healthHealthGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>
  >;
}): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getHealthHealthGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
};
