/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MEXC P2P Aggregator
 * Read-only P2P advertisement monitoring for MEXC
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";
import { computed, unref } from "vue";
import type { MaybeRef } from "vue";
import type {
  AppSchemasAuthErrorResponse,
  GetCsrfTokenEndpointApiV1AuthCsrfTokenGet200,
  HTTPValidationError,
  LoginResponse,
  LogoutApiV1AuthLogoutPost200,
  LogoutApiV1AuthLogoutPostParams,
  RegisterResponse,
  UserLoginRequest,
  UserRegisterRequest,
  UserResponse,
  VerifyEmailResponse,
} from "../client.schemas";
import { customMutator } from ".././mutator";

/**
 * Register a new user account.

Sends verification email with token (24h expiry).
 * @summary Register
 */
export const registerApiV1AuthRegisterPost = (
  userRegisterRequest: MaybeRef<UserRegisterRequest>,
) => {
  userRegisterRequest = unref(userRegisterRequest);

  return customMutator<RegisterResponse>({
    url: `/api/v1/auth/register`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: userRegisterRequest,
  });
};

export const getRegisterApiV1AuthRegisterPostMutationOptions = <
  TError = AppSchemasAuthErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerApiV1AuthRegisterPost>>,
    TError,
    { data: UserRegisterRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof registerApiV1AuthRegisterPost>>,
  TError,
  { data: UserRegisterRequest },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registerApiV1AuthRegisterPost>>,
    { data: UserRegisterRequest }
  > = (props) => {
    const { data } = props ?? {};

    return registerApiV1AuthRegisterPost(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterApiV1AuthRegisterPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof registerApiV1AuthRegisterPost>>
>;
export type RegisterApiV1AuthRegisterPostMutationBody = UserRegisterRequest;
export type RegisterApiV1AuthRegisterPostMutationError =
  | AppSchemasAuthErrorResponse
  | HTTPValidationError;

/**
 * @summary Register
 */
export const useRegisterApiV1AuthRegisterPost = <
  TError = AppSchemasAuthErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerApiV1AuthRegisterPost>>,
    TError,
    { data: UserRegisterRequest },
    TContext
  >;
}): UseMutationReturnType<
  Awaited<ReturnType<typeof registerApiV1AuthRegisterPost>>,
  TError,
  { data: UserRegisterRequest },
  TContext
> => {
  const mutationOptions =
    getRegisterApiV1AuthRegisterPostMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Verify user email address with token from email.
 * @summary Verify Email
 */
export const verifyEmailApiV1AuthVerifyEmailTokenGet = (
  token: MaybeRef<string>,
  signal?: AbortSignal,
) => {
  token = unref(token);

  return customMutator<VerifyEmailResponse>({
    url: `/api/v1/auth/verify-email/${token}`,
    method: "GET",
    signal,
  });
};

export const getVerifyEmailApiV1AuthVerifyEmailTokenGetQueryKey = (
  token: MaybeRef<string>,
) => {
  return ["api", "v1", "auth", "verify-email", token] as const;
};

export const getVerifyEmailApiV1AuthVerifyEmailTokenGetQueryOptions = <
  TData = Awaited<ReturnType<typeof verifyEmailApiV1AuthVerifyEmailTokenGet>>,
  TError = AppSchemasAuthErrorResponse | HTTPValidationError,
>(
  token: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof verifyEmailApiV1AuthVerifyEmailTokenGet>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getVerifyEmailApiV1AuthVerifyEmailTokenGetQueryKey(token);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof verifyEmailApiV1AuthVerifyEmailTokenGet>>
  > = ({ signal }) => verifyEmailApiV1AuthVerifyEmailTokenGet(token, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(token)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof verifyEmailApiV1AuthVerifyEmailTokenGet>>,
    TError,
    TData
  >;
};

export type VerifyEmailApiV1AuthVerifyEmailTokenGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof verifyEmailApiV1AuthVerifyEmailTokenGet>>
>;
export type VerifyEmailApiV1AuthVerifyEmailTokenGetQueryError =
  | AppSchemasAuthErrorResponse
  | HTTPValidationError;

/**
 * @summary Verify Email
 */
export const useVerifyEmailApiV1AuthVerifyEmailTokenGet = <
  TData = Awaited<ReturnType<typeof verifyEmailApiV1AuthVerifyEmailTokenGet>>,
  TError = AppSchemasAuthErrorResponse | HTTPValidationError,
>(
  token: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof verifyEmailApiV1AuthVerifyEmailTokenGet>>,
        TError,
        TData
      >
    >;
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getVerifyEmailApiV1AuthVerifyEmailTokenGetQueryOptions(
    token,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
};

/**
 * Authenticate user and create session.

Sets session_token cookie on success.
 * @summary Login
 */
export const loginApiV1AuthLoginPost = (
  userLoginRequest: MaybeRef<UserLoginRequest>,
) => {
  userLoginRequest = unref(userLoginRequest);

  return customMutator<LoginResponse>({
    url: `/api/v1/auth/login`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: userLoginRequest,
  });
};

export const getLoginApiV1AuthLoginPostMutationOptions = <
  TError = AppSchemasAuthErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginApiV1AuthLoginPost>>,
    TError,
    { data: UserLoginRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginApiV1AuthLoginPost>>,
  TError,
  { data: UserLoginRequest },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginApiV1AuthLoginPost>>,
    { data: UserLoginRequest }
  > = (props) => {
    const { data } = props ?? {};

    return loginApiV1AuthLoginPost(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginApiV1AuthLoginPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginApiV1AuthLoginPost>>
>;
export type LoginApiV1AuthLoginPostMutationBody = UserLoginRequest;
export type LoginApiV1AuthLoginPostMutationError =
  | AppSchemasAuthErrorResponse
  | HTTPValidationError;

/**
 * @summary Login
 */
export const useLoginApiV1AuthLoginPost = <
  TError = AppSchemasAuthErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginApiV1AuthLoginPost>>,
    TError,
    { data: UserLoginRequest },
    TContext
  >;
}): UseMutationReturnType<
  Awaited<ReturnType<typeof loginApiV1AuthLoginPost>>,
  TError,
  { data: UserLoginRequest },
  TContext
> => {
  const mutationOptions = getLoginApiV1AuthLoginPostMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Logout user and clear session.
 * @summary Logout
 */
export const logoutApiV1AuthLogoutPost = (
  params?: MaybeRef<LogoutApiV1AuthLogoutPostParams>,
) => {
  params = unref(params);

  return customMutator<LogoutApiV1AuthLogoutPost200>({
    url: `/api/v1/auth/logout`,
    method: "POST",
    params: unref(params),
  });
};

export const getLogoutApiV1AuthLogoutPostMutationOptions = <
  TError = AppSchemasAuthErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logoutApiV1AuthLogoutPost>>,
    TError,
    { params?: LogoutApiV1AuthLogoutPostParams },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof logoutApiV1AuthLogoutPost>>,
  TError,
  { params?: LogoutApiV1AuthLogoutPostParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logoutApiV1AuthLogoutPost>>,
    { params?: LogoutApiV1AuthLogoutPostParams }
  > = (props) => {
    const { params } = props ?? {};

    return logoutApiV1AuthLogoutPost(params);
  };

  return { mutationFn, ...mutationOptions };
};

export type LogoutApiV1AuthLogoutPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof logoutApiV1AuthLogoutPost>>
>;

export type LogoutApiV1AuthLogoutPostMutationError =
  | AppSchemasAuthErrorResponse
  | HTTPValidationError;

/**
 * @summary Logout
 */
export const useLogoutApiV1AuthLogoutPost = <
  TError = AppSchemasAuthErrorResponse | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logoutApiV1AuthLogoutPost>>,
    TError,
    { params?: LogoutApiV1AuthLogoutPostParams },
    TContext
  >;
}): UseMutationReturnType<
  Awaited<ReturnType<typeof logoutApiV1AuthLogoutPost>>,
  TError,
  { params?: LogoutApiV1AuthLogoutPostParams },
  TContext
> => {
  const mutationOptions = getLogoutApiV1AuthLogoutPostMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Get current authenticated user information.
 * @summary Get Current User Info
 */
export const getCurrentUserInfoApiV1AuthMeGet = (signal?: AbortSignal) => {
  return customMutator<UserResponse>({
    url: `/api/v1/auth/me`,
    method: "GET",
    signal,
  });
};

export const getGetCurrentUserInfoApiV1AuthMeGetQueryKey = () => {
  return ["api", "v1", "auth", "me"] as const;
};

export const getGetCurrentUserInfoApiV1AuthMeGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUserInfoApiV1AuthMeGet>>,
  TError = AppSchemasAuthErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getCurrentUserInfoApiV1AuthMeGet>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getGetCurrentUserInfoApiV1AuthMeGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCurrentUserInfoApiV1AuthMeGet>>
  > = ({ signal }) => getCurrentUserInfoApiV1AuthMeGet(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUserInfoApiV1AuthMeGet>>,
    TError,
    TData
  >;
};

export type GetCurrentUserInfoApiV1AuthMeGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUserInfoApiV1AuthMeGet>>
>;
export type GetCurrentUserInfoApiV1AuthMeGetQueryError =
  AppSchemasAuthErrorResponse;

/**
 * @summary Get Current User Info
 */
export const useGetCurrentUserInfoApiV1AuthMeGet = <
  TData = Awaited<ReturnType<typeof getCurrentUserInfoApiV1AuthMeGet>>,
  TError = AppSchemasAuthErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getCurrentUserInfoApiV1AuthMeGet>>,
      TError,
      TData
    >
  >;
}): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetCurrentUserInfoApiV1AuthMeGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
};

/**
 * Get a fresh CSRF token.

Token is also set as cookie automatically by CSRF middleware.
 * @summary Get Csrf Token Endpoint
 */
export const getCsrfTokenEndpointApiV1AuthCsrfTokenGet = (
  signal?: AbortSignal,
) => {
  return customMutator<GetCsrfTokenEndpointApiV1AuthCsrfTokenGet200>({
    url: `/api/v1/auth/csrf-token`,
    method: "GET",
    signal,
  });
};

export const getGetCsrfTokenEndpointApiV1AuthCsrfTokenGetQueryKey = () => {
  return ["api", "v1", "auth", "csrf-token"] as const;
};

export const getGetCsrfTokenEndpointApiV1AuthCsrfTokenGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getCsrfTokenEndpointApiV1AuthCsrfTokenGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getCsrfTokenEndpointApiV1AuthCsrfTokenGet>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getGetCsrfTokenEndpointApiV1AuthCsrfTokenGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCsrfTokenEndpointApiV1AuthCsrfTokenGet>>
  > = ({ signal }) => getCsrfTokenEndpointApiV1AuthCsrfTokenGet(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCsrfTokenEndpointApiV1AuthCsrfTokenGet>>,
    TError,
    TData
  >;
};

export type GetCsrfTokenEndpointApiV1AuthCsrfTokenGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCsrfTokenEndpointApiV1AuthCsrfTokenGet>>
>;
export type GetCsrfTokenEndpointApiV1AuthCsrfTokenGetQueryError = unknown;

/**
 * @summary Get Csrf Token Endpoint
 */
export const useGetCsrfTokenEndpointApiV1AuthCsrfTokenGet = <
  TData = Awaited<ReturnType<typeof getCsrfTokenEndpointApiV1AuthCsrfTokenGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getCsrfTokenEndpointApiV1AuthCsrfTokenGet>>,
      TError,
      TData
    >
  >;
}): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getGetCsrfTokenEndpointApiV1AuthCsrfTokenGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
};
