/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MEXC P2P Aggregator
 * Read-only P2P advertisement monitoring for MEXC
 * OpenAPI spec version: 0.1.0
 */
export type HealthHealthGet200 = { [key: string]: unknown };

export type GetErrorStatsApiV1AdminErrorsGetParams = {
  hours?: number;
};

export type ToggleSourceApiV1AdminSourcesSourceIdPutParams = {
  enabled: boolean;
};

export type ListAdvertisementsApiV1AdvertisementsGetParams = {
  /**
   * Currency pair
   */
  currency?: string;
  /**
   * BUY or SELL
   */
  direction?: Direction | null;
  /**
   * Filter by payment methods
   */
  payment_methods?: string[] | null;
  /**
   * Minimum amount
   */
  min_amount?: number | null;
  /**
   * Maximum amount
   */
  max_amount?: number | null;
  /**
   * Sort field
   */
  sort_by?: string;
  /**
   * asc or desc
   */
  sort_order?: string;
  /**
   * Max results
   */
  limit?: number;
};

export type GetCsrfTokenEndpointApiV1AuthCsrfTokenGet200 = {
  [key: string]: string;
};

export type LogoutApiV1AuthLogoutPost200 = { [key: string]: string };

export type LogoutApiV1AuthLogoutPostParams = {
  session_token?: string | null;
};

/**
 * Error response schema.
 */
export interface AppSchemasProfileErrorResponse {
  detail: string;
}

/**
 * Response schema for errors.
 */
export interface AppSchemasAuthErrorResponse {
  detail: string;
}

/**
 * Response schema for email verification.
 */
export interface VerifyEmailResponse {
  email: string;
  message: string;
}

export type ValidationErrorLocItem = string | number;

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  ctx?: ValidationErrorCtx;
  input?: unknown;
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

/**
 * Response schema for user data.
 */
export interface UserResponse {
  email: string;
  id: string;
  is_verified: boolean;
  role: string;
}

/**
 * Request schema for user registration.
 */
export interface UserRegisterRequest {
  email: string;
  /**
   * @minLength 8
   * @maxLength 128
   */
  password: string;
}

/**
 * Request schema for user login.
 */
export interface UserLoginRequest {
  email: string;
  password: string;
}

export type TraderProfileUpdateRiskProfile = RiskProfile | null;

export type TraderProfileUpdatePaymentMethods = string[] | null;

export type TraderProfileUpdateMinAmount = number | null;

export type TraderProfileUpdateMaxAmount = number | null;

export type TraderProfileUpdateCurrencyPair = string | null;

export type TraderProfileUpdateCommissionPercent = number | null;

export type TraderProfileUpdateCommissionFixed = number | null;

/**
 * Schema for updating trader profile (all fields optional).
 */
export interface TraderProfileUpdate {
  commission_fixed?: TraderProfileUpdateCommissionFixed;
  commission_percent?: TraderProfileUpdateCommissionPercent;
  currency_pair?: TraderProfileUpdateCurrencyPair;
  max_amount?: TraderProfileUpdateMaxAmount;
  min_amount?: TraderProfileUpdateMinAmount;
  payment_methods?: TraderProfileUpdatePaymentMethods;
  risk_profile?: TraderProfileUpdateRiskProfile;
}

export type TraderProfileResponseMinAmount = number | null;

export type TraderProfileResponseMaxAmount = number | null;

export type TraderProfileResponseCommissionPercent = number | null;

export type TraderProfileResponseCommissionFixed = number | null;

/**
 * Response schema for trader profile.
 */
export interface TraderProfileResponse {
  commission_fixed?: TraderProfileResponseCommissionFixed;
  commission_percent?: TraderProfileResponseCommissionPercent;
  currency_pair?: string;
  id: number;
  max_amount?: TraderProfileResponseMaxAmount;
  min_amount?: TraderProfileResponseMinAmount;
  payment_methods?: string[];
  risk_profile?: RiskProfile;
  user_id: string;
}

/**
 * Status of a data source.
 */
export interface SourceStatus {
  id: string;
  last_updated: string;
  name: string;
  status: string;
  type: string;
}

/**
 * Response with list of source statuses.
 */
export interface SourceStatusResponse {
  sources: SourceStatus[];
}

/**
 * Schema for updating saved filters.
 */
export interface SavedFiltersUpdate {
  filters: AdvertisementFilters;
}

/**
 * Response schema for saved filters.
 */
export interface SavedFiltersResponse {
  filters: AdvertisementFilters;
}

export type RiskProfile = (typeof RiskProfile)[keyof typeof RiskProfile];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RiskProfile = {
  low: "low",
  medium: "medium",
  high: "high",
} as const;

/**
 * Response schema for risk score explanation.
 */
export interface RiskExplanationResponse {
  explanation: string;
  merchant_id: string;
  merchant_name: string;
  risk_category: string;
  risk_score: number;
}

/**
 * Response schema for successful registration.
 */
export interface RegisterResponse {
  email: string;
  message: string;
}

export type MonitoringResponseSourcesItem = { [key: string]: unknown };

export type MonitoringResponseHourlyStats = { [key: string]: unknown };

/**
 * Monitoring statistics response.
 */
export interface MonitoringResponse {
  hourly_stats: MonitoringResponseHourlyStats;
  sources: MonitoringResponseSourcesItem[];
  status: string;
  total_errors_24h: number;
}

export type MerchantResponseRating = number | null;

/**
 * Merchant information in advertisement.
 */
export interface MerchantResponse {
  external_id: string;
  id: string;
  is_verified: boolean;
  name: string;
  rating?: MerchantResponseRating;
  success_rate: number;
  trades_count: number;
}

/**
 * Response schema for successful login.
 */
export interface LoginResponse {
  message?: string;
  user: UserResponse;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type ErrorStatsResponseByType = { [key: string]: number };

/**
 * Error statistics response.
 */
export interface ErrorStatsResponse {
  by_type: ErrorStatsResponseByType;
  period_hours: number;
  total: number;
}

export type Direction = (typeof Direction)[keyof typeof Direction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Direction = {
  BUY: "BUY",
  SELL: "SELL",
} as const;

/**
 * Information about a payment method / bank.
 */
export interface BankInfo {
  category: string;
  id: string;
  name: string;
}

/**
 * Response with list of available banks.
 */
export interface BanksListResponse {
  banks: BankInfo[];
}

export type AdvertisementResponseSpread = number | null;

export type AdvertisementResponseRiskScore = number | null;

export type AdvertisementResponseRiskCategory = string | null;

export type AdvertisementResponseNetYield = number | null;

/**
 * Advertisement response schema.
 */
export interface AdvertisementResponse {
  currency: string;
  direction: string;
  external_id: string;
  fetched_at: string;
  id: string;
  is_active: boolean;
  max_limit: number;
  merchant: MerchantResponse;
  min_limit: number;
  net_yield?: AdvertisementResponseNetYield;
  payment_methods: string[];
  price: number;
  risk_category?: AdvertisementResponseRiskCategory;
  risk_score?: AdvertisementResponseRiskScore;
  spread?: AdvertisementResponseSpread;
  volume: number;
}

export type AdvertisementListResponseReferencePrice = number | null;

export type AdvertisementListResponseLastUpdated = string | null;

/**
 * List of advertisements with metadata.
 */
export interface AdvertisementListResponse {
  items: AdvertisementResponse[];
  last_updated?: AdvertisementListResponseLastUpdated;
  reference_price?: AdvertisementListResponseReferencePrice;
  total: number;
}

export type AdvertisementFiltersPaymentMethods = string[] | null;

export type AdvertisementFiltersMinTrades = number | null;

export type AdvertisementFiltersMinRating = number | null;

export type AdvertisementFiltersMinAmount = number | null;

export type AdvertisementFiltersMaxAmount = number | null;

/**
 * Filter criteria for advertisements.
 */
export interface AdvertisementFilters {
  max_amount?: AdvertisementFiltersMaxAmount;
  min_amount?: AdvertisementFiltersMinAmount;
  min_rating?: AdvertisementFiltersMinRating;
  min_trades?: AdvertisementFiltersMinTrades;
  payment_methods?: AdvertisementFiltersPaymentMethods;
}
