/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MEXC P2P Aggregator
 * Read-only P2P advertisement monitoring for MEXC
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";
import { unref } from "vue";
import type { MaybeRef } from "vue";
import type {
  BlacklistAddRequest,
  BlacklistEntry,
  BlacklistResponse,
  HTTPValidationError,
  RemoveFromBlacklistApiV1BlacklistMerchantIdDelete200,
} from "../client.schemas";
import { customMutator } from ".././mutator";

/**
 * Get user's merchant blacklist.
 * @summary Get Blacklist
 */
export const getBlacklistApiV1BlacklistGet = (signal?: AbortSignal) => {
  return customMutator<BlacklistResponse>({
    url: `/api/v1/blacklist`,
    method: "GET",
    signal,
  });
};

export const getGetBlacklistApiV1BlacklistGetQueryKey = () => {
  return ["api", "v1", "blacklist"] as const;
};

export const getGetBlacklistApiV1BlacklistGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getBlacklistApiV1BlacklistGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getBlacklistApiV1BlacklistGet>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getGetBlacklistApiV1BlacklistGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getBlacklistApiV1BlacklistGet>>
  > = ({ signal }) => getBlacklistApiV1BlacklistGet(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getBlacklistApiV1BlacklistGet>>,
    TError,
    TData
  >;
};

export type GetBlacklistApiV1BlacklistGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBlacklistApiV1BlacklistGet>>
>;
export type GetBlacklistApiV1BlacklistGetQueryError = unknown;

/**
 * @summary Get Blacklist
 */
export const useGetBlacklistApiV1BlacklistGet = <
  TData = Awaited<ReturnType<typeof getBlacklistApiV1BlacklistGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getBlacklistApiV1BlacklistGet>>,
      TError,
      TData
    >
  >;
}): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetBlacklistApiV1BlacklistGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
};

/**
 * Add merchant to blacklist.
 * @summary Add To Blacklist
 */
export const addToBlacklistApiV1BlacklistPost = (
  blacklistAddRequest: MaybeRef<BlacklistAddRequest>,
) => {
  blacklistAddRequest = unref(blacklistAddRequest);

  return customMutator<BlacklistEntry>({
    url: `/api/v1/blacklist`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: blacklistAddRequest,
  });
};

export const getAddToBlacklistApiV1BlacklistPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addToBlacklistApiV1BlacklistPost>>,
    TError,
    { data: BlacklistAddRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addToBlacklistApiV1BlacklistPost>>,
  TError,
  { data: BlacklistAddRequest },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addToBlacklistApiV1BlacklistPost>>,
    { data: BlacklistAddRequest }
  > = (props) => {
    const { data } = props ?? {};

    return addToBlacklistApiV1BlacklistPost(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddToBlacklistApiV1BlacklistPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof addToBlacklistApiV1BlacklistPost>>
>;
export type AddToBlacklistApiV1BlacklistPostMutationBody = BlacklistAddRequest;
export type AddToBlacklistApiV1BlacklistPostMutationError = HTTPValidationError;

/**
 * @summary Add To Blacklist
 */
export const useAddToBlacklistApiV1BlacklistPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addToBlacklistApiV1BlacklistPost>>,
    TError,
    { data: BlacklistAddRequest },
    TContext
  >;
}): UseMutationReturnType<
  Awaited<ReturnType<typeof addToBlacklistApiV1BlacklistPost>>,
  TError,
  { data: BlacklistAddRequest },
  TContext
> => {
  const mutationOptions =
    getAddToBlacklistApiV1BlacklistPostMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Remove merchant from blacklist.
 * @summary Remove From Blacklist
 */
export const removeFromBlacklistApiV1BlacklistMerchantIdDelete = (
  merchantId: MaybeRef<string>,
) => {
  merchantId = unref(merchantId);

  return customMutator<RemoveFromBlacklistApiV1BlacklistMerchantIdDelete200>({
    url: `/api/v1/blacklist/${merchantId}`,
    method: "DELETE",
  });
};

export const getRemoveFromBlacklistApiV1BlacklistMerchantIdDeleteMutationOptions =
  <TError = HTTPValidationError, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof removeFromBlacklistApiV1BlacklistMerchantIdDelete>
      >,
      TError,
      { merchantId: string },
      TContext
    >;
  }): UseMutationOptions<
    Awaited<
      ReturnType<typeof removeFromBlacklistApiV1BlacklistMerchantIdDelete>
    >,
    TError,
    { merchantId: string },
    TContext
  > => {
    const { mutation: mutationOptions } = options ?? {};

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<typeof removeFromBlacklistApiV1BlacklistMerchantIdDelete>
      >,
      { merchantId: string }
    > = (props) => {
      const { merchantId } = props ?? {};

      return removeFromBlacklistApiV1BlacklistMerchantIdDelete(merchantId);
    };

    return { mutationFn, ...mutationOptions };
  };

export type RemoveFromBlacklistApiV1BlacklistMerchantIdDeleteMutationResult =
  NonNullable<
    Awaited<
      ReturnType<typeof removeFromBlacklistApiV1BlacklistMerchantIdDelete>
    >
  >;

export type RemoveFromBlacklistApiV1BlacklistMerchantIdDeleteMutationError =
  HTTPValidationError;

/**
 * @summary Remove From Blacklist
 */
export const useRemoveFromBlacklistApiV1BlacklistMerchantIdDelete = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<
      ReturnType<typeof removeFromBlacklistApiV1BlacklistMerchantIdDelete>
    >,
    TError,
    { merchantId: string },
    TContext
  >;
}): UseMutationReturnType<
  Awaited<ReturnType<typeof removeFromBlacklistApiV1BlacklistMerchantIdDelete>>,
  TError,
  { merchantId: string },
  TContext
> => {
  const mutationOptions =
    getRemoveFromBlacklistApiV1BlacklistMerchantIdDeleteMutationOptions(
      options,
    );

  return useMutation(mutationOptions);
};
