/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MEXC P2P Aggregator
 * Read-only P2P advertisement monitoring for MEXC
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/vue-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";
import { computed, unref } from "vue";
import type { MaybeRef } from "vue";
import type {
  HTTPValidationError,
  RiskExplanationResponse,
} from "../client.schemas";
import { customMutator } from ".././mutator";

/**
 * Get risk score explanation for a merchant.

Returns cached LLM explanation if available.
 * @summary Get Risk Explanation
 */
export const getRiskExplanationApiV1ScoringMerchantIdExplainGet = (
  merchantId: MaybeRef<string>,
  signal?: AbortSignal,
) => {
  merchantId = unref(merchantId);

  return customMutator<RiskExplanationResponse>({
    url: `/api/v1/scoring/${merchantId}/explain`,
    method: "GET",
    signal,
  });
};

export const getGetRiskExplanationApiV1ScoringMerchantIdExplainGetQueryKey = (
  merchantId: MaybeRef<string>,
) => {
  return ["api", "v1", "scoring", merchantId, "explain"] as const;
};

export const getGetRiskExplanationApiV1ScoringMerchantIdExplainGetQueryOptions =
  <
    TData = Awaited<
      ReturnType<typeof getRiskExplanationApiV1ScoringMerchantIdExplainGet>
    >,
    TError = HTTPValidationError,
  >(
    merchantId: MaybeRef<string>,
    options?: {
      query?: Partial<
        UseQueryOptions<
          Awaited<
            ReturnType<
              typeof getRiskExplanationApiV1ScoringMerchantIdExplainGet
            >
          >,
          TError,
          TData
        >
      >;
    },
  ) => {
    const { query: queryOptions } = options ?? {};

    const queryKey =
      getGetRiskExplanationApiV1ScoringMerchantIdExplainGetQueryKey(merchantId);

    const queryFn: QueryFunction<
      Awaited<
        ReturnType<typeof getRiskExplanationApiV1ScoringMerchantIdExplainGet>
      >
    > = ({ signal }) =>
      getRiskExplanationApiV1ScoringMerchantIdExplainGet(merchantId, signal);

    return {
      queryKey,
      queryFn,
      enabled: computed(() => !!unref(merchantId)),
      ...queryOptions,
    } as UseQueryOptions<
      Awaited<
        ReturnType<typeof getRiskExplanationApiV1ScoringMerchantIdExplainGet>
      >,
      TError,
      TData
    >;
  };

export type GetRiskExplanationApiV1ScoringMerchantIdExplainGetQueryResult =
  NonNullable<
    Awaited<
      ReturnType<typeof getRiskExplanationApiV1ScoringMerchantIdExplainGet>
    >
  >;
export type GetRiskExplanationApiV1ScoringMerchantIdExplainGetQueryError =
  HTTPValidationError;

/**
 * @summary Get Risk Explanation
 */
export const useGetRiskExplanationApiV1ScoringMerchantIdExplainGet = <
  TData = Awaited<
    ReturnType<typeof getRiskExplanationApiV1ScoringMerchantIdExplainGet>
  >,
  TError = HTTPValidationError,
>(
  merchantId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getRiskExplanationApiV1ScoringMerchantIdExplainGet>
        >,
        TError,
        TData
      >
    >;
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getGetRiskExplanationApiV1ScoringMerchantIdExplainGetQueryOptions(
      merchantId,
      options,
    );

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
};
