/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MEXC P2P Aggregator
 * Read-only P2P advertisement monitoring for MEXC
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";
import { unref } from "vue";
import type { MaybeRef } from "vue";
import type {
  HTTPValidationError,
  RecordViewRequest,
  ViewHistoryEntry,
  ViewHistoryResponse,
} from "../client.schemas";
import { customMutator } from ".././mutator";

/**
 * Get user's recent view history (last 50).
 * @summary Get View History
 */
export const getViewHistoryApiV1HistoryGet = (signal?: AbortSignal) => {
  return customMutator<ViewHistoryResponse>({
    url: `/api/v1/history`,
    method: "GET",
    signal,
  });
};

export const getGetViewHistoryApiV1HistoryGetQueryKey = () => {
  return ["api", "v1", "history"] as const;
};

export const getGetViewHistoryApiV1HistoryGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getViewHistoryApiV1HistoryGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getViewHistoryApiV1HistoryGet>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getGetViewHistoryApiV1HistoryGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getViewHistoryApiV1HistoryGet>>
  > = ({ signal }) => getViewHistoryApiV1HistoryGet(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getViewHistoryApiV1HistoryGet>>,
    TError,
    TData
  >;
};

export type GetViewHistoryApiV1HistoryGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getViewHistoryApiV1HistoryGet>>
>;
export type GetViewHistoryApiV1HistoryGetQueryError = unknown;

/**
 * @summary Get View History
 */
export const useGetViewHistoryApiV1HistoryGet = <
  TData = Awaited<ReturnType<typeof getViewHistoryApiV1HistoryGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getViewHistoryApiV1HistoryGet>>,
      TError,
      TData
    >
  >;
}): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetViewHistoryApiV1HistoryGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
};

/**
 * Record that user viewed an advertisement.
 * @summary Record View
 */
export const recordViewApiV1HistoryPost = (
  recordViewRequest: MaybeRef<RecordViewRequest>,
) => {
  recordViewRequest = unref(recordViewRequest);

  return customMutator<ViewHistoryEntry>({
    url: `/api/v1/history`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: recordViewRequest,
  });
};

export const getRecordViewApiV1HistoryPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof recordViewApiV1HistoryPost>>,
    TError,
    { data: RecordViewRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof recordViewApiV1HistoryPost>>,
  TError,
  { data: RecordViewRequest },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof recordViewApiV1HistoryPost>>,
    { data: RecordViewRequest }
  > = (props) => {
    const { data } = props ?? {};

    return recordViewApiV1HistoryPost(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type RecordViewApiV1HistoryPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof recordViewApiV1HistoryPost>>
>;
export type RecordViewApiV1HistoryPostMutationBody = RecordViewRequest;
export type RecordViewApiV1HistoryPostMutationError = HTTPValidationError;

/**
 * @summary Record View
 */
export const useRecordViewApiV1HistoryPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof recordViewApiV1HistoryPost>>,
    TError,
    { data: RecordViewRequest },
    TContext
  >;
}): UseMutationReturnType<
  Awaited<ReturnType<typeof recordViewApiV1HistoryPost>>,
  TError,
  { data: RecordViewRequest },
  TContext
> => {
  const mutationOptions = getRecordViewApiV1HistoryPostMutationOptions(options);

  return useMutation(mutationOptions);
};
