/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MEXC P2P Aggregator
 * Read-only P2P advertisement monitoring for MEXC
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/vue-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";
import { computed, unref } from "vue";
import type { MaybeRef } from "vue";
import type {
  AdvertisementListResponse,
  AdvertisementResponse,
  HTTPValidationError,
  ListAdvertisementsApiV1AdvertisementsGetParams,
} from "../client.schemas";
import { customMutator } from ".././mutator";

/**
 * List advertisements with filtering and sorting.
 * @summary List Advertisements
 */
export const listAdvertisementsApiV1AdvertisementsGet = (
  params?: MaybeRef<ListAdvertisementsApiV1AdvertisementsGetParams>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customMutator<AdvertisementListResponse>({
    url: `/api/v1/advertisements`,
    method: "GET",
    params: unref(params),
    signal,
  });
};

export const getListAdvertisementsApiV1AdvertisementsGetQueryKey = (
  params?: MaybeRef<ListAdvertisementsApiV1AdvertisementsGetParams>,
) => {
  return ["api", "v1", "advertisements", ...(params ? [params] : [])] as const;
};

export const getListAdvertisementsApiV1AdvertisementsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof listAdvertisementsApiV1AdvertisementsGet>>,
  TError = HTTPValidationError,
>(
  params?: MaybeRef<ListAdvertisementsApiV1AdvertisementsGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listAdvertisementsApiV1AdvertisementsGet>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getListAdvertisementsApiV1AdvertisementsGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listAdvertisementsApiV1AdvertisementsGet>>
  > = ({ signal }) => listAdvertisementsApiV1AdvertisementsGet(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAdvertisementsApiV1AdvertisementsGet>>,
    TError,
    TData
  >;
};

export type ListAdvertisementsApiV1AdvertisementsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAdvertisementsApiV1AdvertisementsGet>>
>;
export type ListAdvertisementsApiV1AdvertisementsGetQueryError =
  HTTPValidationError;

/**
 * @summary List Advertisements
 */
export const useListAdvertisementsApiV1AdvertisementsGet = <
  TData = Awaited<ReturnType<typeof listAdvertisementsApiV1AdvertisementsGet>>,
  TError = HTTPValidationError,
>(
  params?: MaybeRef<ListAdvertisementsApiV1AdvertisementsGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listAdvertisementsApiV1AdvertisementsGet>>,
        TError,
        TData
      >
    >;
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getListAdvertisementsApiV1AdvertisementsGetQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
};

/**
 * Get single advertisement details.
 * @summary Get Advertisement
 */
export const getAdvertisementApiV1AdvertisementsAdIdGet = (
  adId: MaybeRef<string>,
  signal?: AbortSignal,
) => {
  adId = unref(adId);

  return customMutator<AdvertisementResponse>({
    url: `/api/v1/advertisements/${adId}`,
    method: "GET",
    signal,
  });
};

export const getGetAdvertisementApiV1AdvertisementsAdIdGetQueryKey = (
  adId: MaybeRef<string>,
) => {
  return ["api", "v1", "advertisements", adId] as const;
};

export const getGetAdvertisementApiV1AdvertisementsAdIdGetQueryOptions = <
  TData = Awaited<
    ReturnType<typeof getAdvertisementApiV1AdvertisementsAdIdGet>
  >,
  TError = HTTPValidationError,
>(
  adId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdvertisementApiV1AdvertisementsAdIdGet>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getGetAdvertisementApiV1AdvertisementsAdIdGetQueryKey(adId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAdvertisementApiV1AdvertisementsAdIdGet>>
  > = ({ signal }) => getAdvertisementApiV1AdvertisementsAdIdGet(adId, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(adId)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdvertisementApiV1AdvertisementsAdIdGet>>,
    TError,
    TData
  >;
};

export type GetAdvertisementApiV1AdvertisementsAdIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdvertisementApiV1AdvertisementsAdIdGet>>
>;
export type GetAdvertisementApiV1AdvertisementsAdIdGetQueryError =
  HTTPValidationError;

/**
 * @summary Get Advertisement
 */
export const useGetAdvertisementApiV1AdvertisementsAdIdGet = <
  TData = Awaited<
    ReturnType<typeof getAdvertisementApiV1AdvertisementsAdIdGet>
  >,
  TError = HTTPValidationError,
>(
  adId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAdvertisementApiV1AdvertisementsAdIdGet>>,
        TError,
        TData
      >
    >;
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getGetAdvertisementApiV1AdvertisementsAdIdGetQueryOptions(adId, options);

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
};
