"""Initial migration

Revision ID: 96090f785ff2
Revises: 
Create Date: 2026-03-26 15:19:22.082297

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96090f785ff2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False, comment='ID мерчанта на бирже'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('trades_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=True, comment='0 to 1'),
    sa.Column('closing_speed', sa.Float(), nullable=True, comment='seconds'),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('polling_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('hour_bucket', sa.DateTime(timezone=True), nullable=False, comment='Truncated to hour for aggregation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('advertisements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False, comment='ID объявления на бирже'),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('min_limit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_limit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_methods', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.SmallInteger(), nullable=True),
    sa.Column('risk_category', sa.String(length=10), nullable=True, comment='low/medium/high'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_ads_currency_direction_active', 'advertisements', ['currency', 'direction', 'is_active'], unique=False)
    op.create_index('ix_ads_fetched_at', 'advertisements', ['fetched_at'], unique=False)
    op.create_index('ix_ads_merchant_id', 'advertisements', ['merchant_id'], unique=False)
    op.create_table('saved_filters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('filters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('trader_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('payment_methods', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency_pair', sa.String(length=20), nullable=False),
    sa.Column('risk_profile', sa.String(length=10), nullable=False),
    sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('commission_fixed', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trader_profiles')
    op.drop_table('saved_filters')
    op.drop_index('ix_ads_merchant_id', table_name='advertisements')
    op.drop_index('ix_ads_fetched_at', table_name='advertisements')
    op.drop_index('ix_ads_currency_direction_active', table_name='advertisements')
    op.drop_table('advertisements')
    op.drop_table('users')
    op.drop_table('polling_errors')
    op.drop_table('merchants')
    # ### end Alembic commands ###
