/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MEXC P2P Aggregator
 * Read-only P2P advertisement monitoring for MEXC
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";
import { unref } from "vue";
import type { MaybeRef } from "vue";
import type {
  ErrorStatsResponse,
  GetErrorStatsApiV1AdminErrorsGetParams,
  HTTPValidationError,
  MonitoringResponse,
  SourceStatus,
  SourceStatusResponse,
  ToggleSourceApiV1AdminSourcesSourceIdPutParams,
} from "../client.schemas";
import { customMutator } from ".././mutator";

/**
 * Get status of all P2P data sources.

Admin only.
 * @summary Get Sources Status
 */
export const getSourcesStatusApiV1AdminSourcesGet = (signal?: AbortSignal) => {
  return customMutator<SourceStatusResponse>({
    url: `/api/v1/admin/sources`,
    method: "GET",
    signal,
  });
};

export const getGetSourcesStatusApiV1AdminSourcesGetQueryKey = () => {
  return ["api", "v1", "admin", "sources"] as const;
};

export const getGetSourcesStatusApiV1AdminSourcesGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getSourcesStatusApiV1AdminSourcesGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getSourcesStatusApiV1AdminSourcesGet>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getGetSourcesStatusApiV1AdminSourcesGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSourcesStatusApiV1AdminSourcesGet>>
  > = ({ signal }) => getSourcesStatusApiV1AdminSourcesGet(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSourcesStatusApiV1AdminSourcesGet>>,
    TError,
    TData
  >;
};

export type GetSourcesStatusApiV1AdminSourcesGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSourcesStatusApiV1AdminSourcesGet>>
>;
export type GetSourcesStatusApiV1AdminSourcesGetQueryError = unknown;

/**
 * @summary Get Sources Status
 */
export const useGetSourcesStatusApiV1AdminSourcesGet = <
  TData = Awaited<ReturnType<typeof getSourcesStatusApiV1AdminSourcesGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getSourcesStatusApiV1AdminSourcesGet>>,
      TError,
      TData
    >
  >;
}): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getGetSourcesStatusApiV1AdminSourcesGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
};

/**
 * Enable or disable a data source.

Admin only.
 * @summary Toggle Source
 */
export const toggleSourceApiV1AdminSourcesSourceIdPut = (
  sourceId: MaybeRef<string>,
  params: MaybeRef<ToggleSourceApiV1AdminSourcesSourceIdPutParams>,
) => {
  sourceId = unref(sourceId);
  params = unref(params);

  return customMutator<SourceStatus>({
    url: `/api/v1/admin/sources/${sourceId}`,
    method: "PUT",
    params: unref(params),
  });
};

export const getToggleSourceApiV1AdminSourcesSourceIdPutMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof toggleSourceApiV1AdminSourcesSourceIdPut>>,
    TError,
    {
      sourceId: string;
      params: ToggleSourceApiV1AdminSourcesSourceIdPutParams;
    },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof toggleSourceApiV1AdminSourcesSourceIdPut>>,
  TError,
  { sourceId: string; params: ToggleSourceApiV1AdminSourcesSourceIdPutParams },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof toggleSourceApiV1AdminSourcesSourceIdPut>>,
    { sourceId: string; params: ToggleSourceApiV1AdminSourcesSourceIdPutParams }
  > = (props) => {
    const { sourceId, params } = props ?? {};

    return toggleSourceApiV1AdminSourcesSourceIdPut(sourceId, params);
  };

  return { mutationFn, ...mutationOptions };
};

export type ToggleSourceApiV1AdminSourcesSourceIdPutMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof toggleSourceApiV1AdminSourcesSourceIdPut>>
  >;

export type ToggleSourceApiV1AdminSourcesSourceIdPutMutationError =
  HTTPValidationError;

/**
 * @summary Toggle Source
 */
export const useToggleSourceApiV1AdminSourcesSourceIdPut = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof toggleSourceApiV1AdminSourcesSourceIdPut>>,
    TError,
    {
      sourceId: string;
      params: ToggleSourceApiV1AdminSourcesSourceIdPutParams;
    },
    TContext
  >;
}): UseMutationReturnType<
  Awaited<ReturnType<typeof toggleSourceApiV1AdminSourcesSourceIdPut>>,
  TError,
  { sourceId: string; params: ToggleSourceApiV1AdminSourcesSourceIdPutParams },
  TContext
> => {
  const mutationOptions =
    getToggleSourceApiV1AdminSourcesSourceIdPutMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Get monitoring statistics for the last 24 hours.

Admin only.
 * @summary Get Monitoring Stats
 */
export const getMonitoringStatsApiV1AdminMonitoringGet = (
  signal?: AbortSignal,
) => {
  return customMutator<MonitoringResponse>({
    url: `/api/v1/admin/monitoring`,
    method: "GET",
    signal,
  });
};

export const getGetMonitoringStatsApiV1AdminMonitoringGetQueryKey = () => {
  return ["api", "v1", "admin", "monitoring"] as const;
};

export const getGetMonitoringStatsApiV1AdminMonitoringGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getMonitoringStatsApiV1AdminMonitoringGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getMonitoringStatsApiV1AdminMonitoringGet>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getGetMonitoringStatsApiV1AdminMonitoringGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMonitoringStatsApiV1AdminMonitoringGet>>
  > = ({ signal }) => getMonitoringStatsApiV1AdminMonitoringGet(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMonitoringStatsApiV1AdminMonitoringGet>>,
    TError,
    TData
  >;
};

export type GetMonitoringStatsApiV1AdminMonitoringGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMonitoringStatsApiV1AdminMonitoringGet>>
>;
export type GetMonitoringStatsApiV1AdminMonitoringGetQueryError = unknown;

/**
 * @summary Get Monitoring Stats
 */
export const useGetMonitoringStatsApiV1AdminMonitoringGet = <
  TData = Awaited<ReturnType<typeof getMonitoringStatsApiV1AdminMonitoringGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getMonitoringStatsApiV1AdminMonitoringGet>>,
      TError,
      TData
    >
  >;
}): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getGetMonitoringStatsApiV1AdminMonitoringGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
};

/**
 * Get detailed error statistics.

Admin only.
 * @summary Get Error Stats
 */
export const getErrorStatsApiV1AdminErrorsGet = (
  params?: MaybeRef<GetErrorStatsApiV1AdminErrorsGetParams>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customMutator<ErrorStatsResponse>({
    url: `/api/v1/admin/errors`,
    method: "GET",
    params: unref(params),
    signal,
  });
};

export const getGetErrorStatsApiV1AdminErrorsGetQueryKey = (
  params?: MaybeRef<GetErrorStatsApiV1AdminErrorsGetParams>,
) => {
  return ["api", "v1", "admin", "errors", ...(params ? [params] : [])] as const;
};

export const getGetErrorStatsApiV1AdminErrorsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getErrorStatsApiV1AdminErrorsGet>>,
  TError = HTTPValidationError,
>(
  params?: MaybeRef<GetErrorStatsApiV1AdminErrorsGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getErrorStatsApiV1AdminErrorsGet>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getGetErrorStatsApiV1AdminErrorsGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getErrorStatsApiV1AdminErrorsGet>>
  > = ({ signal }) => getErrorStatsApiV1AdminErrorsGet(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getErrorStatsApiV1AdminErrorsGet>>,
    TError,
    TData
  >;
};

export type GetErrorStatsApiV1AdminErrorsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getErrorStatsApiV1AdminErrorsGet>>
>;
export type GetErrorStatsApiV1AdminErrorsGetQueryError = HTTPValidationError;

/**
 * @summary Get Error Stats
 */
export const useGetErrorStatsApiV1AdminErrorsGet = <
  TData = Awaited<ReturnType<typeof getErrorStatsApiV1AdminErrorsGet>>,
  TError = HTTPValidationError,
>(
  params?: MaybeRef<GetErrorStatsApiV1AdminErrorsGetParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getErrorStatsApiV1AdminErrorsGet>>,
        TError,
        TData
      >
    >;
  },
): UseQueryReturnType<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetErrorStatsApiV1AdminErrorsGetQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = unref(queryOptions).queryKey as QueryKey;

  return query;
};
